const ROLES = {
    CITIZEN: "CITIZEN",
    AUTHORITY: "AUTHORITY",
    ADMIN: "ADMIN",
};

const COMPLAINT_STATUS = {
    SUBMITTED: "SUBMITTED",
    VERIFIED: "VERIFIED",
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    RESOLVED: "RESOLVED",
    CLOSED: "CLOSED",
    REJECTED: "REJECTED",
    ESCALATED: "ESCALATED",
};

const PRIORITY = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
};

const ELIGIBILITY_STATUS = {
    ELIGIBLE: "ELIGIBLE",
    NOT_ELIGIBLE: "NOT_ELIGIBLE",
    POTENTIALLY_ELIGIBLE: "POTENTIALLY_ELIGIBLE",
    INSUFFICIENT_INFORMATION: "INSUFFICIENT_INFORMATION",
};

module.exports = {
    ROLES,
    COMPLAINT_STATUS,
    PRIORITY,
    ELIGIBILITY_STATUS,
};